### ISSUE TITLE
Unable to read history

### ISSUE THREAD

**Issue by Akegata** [imrahil/OctoPrint-PrintHistory#17]
My History tab is empty, and I get this in my log:
```
2015-09-06 15:42:38,084 - octoprint - ERROR - Exception on /plugin/printhistory/history [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/__init__.py", line 64, in getHistoryData
    raise IOError("Couldn't read history data from {path}".format(path=self._history_file_path))
IOError: Couldn't read history data from /home/pi/.octoprint/data/printhistory/history.yaml
```

The history.yaml file is accessible to the pi user (and cat'ing it works fine):
```
pi@octopi ~/.octoprint/logs $ ls -lh /home/pi/.octoprint/data/printhistory/history.yaml
-rw-r--r-- 1 pi pi 21K Sep  6 15:42 /home/pi/.octoprint/data/printhistory/history.yaml
```

octoprint is run by the pi user:
```
pi@octopi ~/.octoprint/logs $ ps auxwwf | grep octoprint
pi        2304 18.0  7.6 170728 29236 ?        Sl   10:35  59:12 /home/pi/oprint/bin/python /home/pi/oprint/bin/octoprint --host=127.0.0.1 --port=5000
```

It seems like this would be a permissions issue, but I can't figure out what exactly is causing this.

**Comment by imrahil** [comment]
could you provide file content from history.yaml?

**Comment by Akegata** [comment]
```
1440021173752:
  fileName: close_support.gcode
  note: ''
  success: false
  timestamp: 1440021173.75264
1440021367992:
  filamentLength: 3794.7619700000037
  filamentVolume: 9.127472187915986
  fileName: close_support.gcode
  note: ''
  success: false
  timestamp: 1440021367.992722
1440021788931:
  filamentLength: 3794.7619700000037
  filamentVolume: 9.127472187915986
  fileName: close_support.gcode
  note: ''
  success: false
  timestamp: 1440021788.931184
1440022561742:
  filamentLength: 3794.7619700000037
  filamentVolume: 9.127472187915986
  fileName: close_support.gcode
  note: ''
  success: false
  timestamp: 1440022561.742791
1440023760093:
  fileName: x-carriage.gcode
  note: ''
  success: false
  timestamp: 1440023760.093949
1440024023850:
  filamentLength: 7991.208250000097
  filamentVolume: 19.221108366309625
  fileName: x-carriage.gcode
  note: ''
  success: false
  timestamp: 1440024023.850569
1440024444768:
  filamentLength: 7991.208250000097
  filamentVolume: 19.221108366309625
  fileName: x-carriage.gcode
  note: ''
  success: false
  timestamp: 1440024444.768997
1440024944401:
  filamentLength: 7991.208250000097
  filamentVolume: 19.221108366309625
  fileName: x-carriage.gcode
  note: ''
  success: false
  timestamp: 1440024944.401018
1440025436128:
  fileName: vert_Y_endstop_part.gcode
  note: ''
  success: false
  timestamp: 1440025436.128456
1440027885402:
  fileName: vert_Y_endstop_part.gcode
  note: ''
  printTime: 2429.737524986267
  success: true
  timestamp: 1440027885.402439
1440145928911:
  filamentLength: 3794.7619700000037
  filamentVolume: 9.127472187915986
  fileName: close_support.gcode
  note: ''
  success: false
  timestamp: 1440145928.911154
1440353388859:
  filamentLength: 8145.811940000442
  filamentVolume: 19.592973819738138
  fileName: x_carriage_30mm.gcode
  note: ''
  success: false
  timestamp: 1440353388.859874
1440366222027:
  filamentLength: 8145.811940000442
  filamentVolume: 19.592973819738138
  fileName: x_carriage_30mm.gcode
  note: ''
  printTime: 12669.646673202515
  success: true
  timestamp: 1440366222.027545
1440666000852:
  fileName: Universal_filament_filter.gcode
  note: ''
  printTime: 1837.9013559818268
  success: true
  timestamp: 1440666000.852564
1440666297804:
  fileName: Universal_filament_filter.gcode
  note: ''
  success: false
  timestamp: 1440666297.804822
1440667874150:
  filamentLength: 808.000299999991
  filamentVolume: 1.9434684769115265
  fileName: Universal_filament_filter.gcode
  note: ''
  printTime: 1546.6094861030579
  success: true
  timestamp: 1440667874.150853
1440670211283:
  fileName: Universal_filament_filter.gcode
  note: ''
  printTime: 1273.6418800354004
  success: true
  timestamp: 1440670211.283365
1440670962210:
  fileName: Universal_filament_filter.gcode
  note: ''
  success: false
  timestamp: 1440670962.210542
1440675023400:
  filamentLength: 808.000299999991
  filamentVolume: 1.9434684769115265
  fileName: Universal_filament_filter.gcode
  note: ''
  success: false
  timestamp: 1440675023.400816
1440676444084:
  fileName: Universal_filament_filter.gcode
  note: ''
  printTime: 1260.5921640396118
  success: true
  timestamp: 1440676444.084249
1440679758714:
  fileName: bearing_pin_x4_(1).gcode
  note: ''
  printTime: 2740.3028090000153
  success: true
  timestamp: 1440679758.714842
1440680273881:
  fileName: filament_spool_holder_dolly_for_608z_bearing_extra_support_2x.gcode
  note: ''
  success: false
  timestamp: 1440680273.881234
1440705372598:
  filamentLength: 14714.636649998454
  filamentVolume: 35.392848837406795
  fileName: filament_spool_holder_dolly_for_608z_bearing_extra_support_2x.gcode
  note: ''
  printTime: 24919.40575003624
  success: true
  timestamp: 1440705372.59806
1440707210895:
  fileName: knob.gcode
  note: ''
  printTime: 1514.9948959350586
  success: true
  timestamp: 1440707210.895208
1440727932251:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  printTime: 20655.069233179092
  success: true
  timestamp: 1440727932.251748
1440743290307:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440743290.307493
1440765441135:
  fileName: smallgearmod_fixed.gcode
  note: ''
  success: false
  timestamp: 1440765441.135734
1440766995309:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  success: false
  timestamp: 1440766995.309893
1440767226372:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  success: false
  timestamp: 1440767226.372113
1440767785893:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  success: false
  timestamp: 1440767785.893792
1440784399112:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  printTime: 16394.54786014557
  success: true
  timestamp: 1440784399.112058
1440795051023:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  printTime: 16394.54786014557
  success: false
  timestamp: 1440795051.023502
1440811384772:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  printTime: 16319.585672855377
  success: true
  timestamp: 1440811384.772869
1440958606616:
  filamentLength: 18098.077530001076
  filamentVolume: 43.53097786258038
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440958606.616556
1440959303760:
  filamentLength: 18098.077530001076
  filamentVolume: 43.53097786258038
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440959303.760591
1440959631469:
  filamentLength: 18098.077530001076
  filamentVolume: 43.53097786258038
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440959631.469314
1440968713814:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440968713.814587
1440979639629:
  filamentLength: 16938.415650000163
  filamentVolume: 40.74166416101646
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440979639.629116
1440979929272:
  filamentLength: 16938.415650000163
  filamentVolume: 40.74166416101646
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440979929.272138
1440979998960:
  filamentLength: 16938.415650000163
  filamentVolume: 40.74166416101646
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440979998.960237
1440980387081:
  filamentLength: 16938.415650000163
  filamentVolume: 40.74166416101646
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1440980387.081062
1440980440775:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  printTime: 16319.585672855377
  success: false
  timestamp: 1440980440.775334
1441008341954:
  fileName: fan_shroud.gcode
  note: ''
  success: false
  timestamp: 1441008341.954902
1441015466408:
  fileName: fan_shroud.gcode
  note: ''
  printTime: 7089.889451980591
  success: true
  timestamp: 1441015466.408219
1441026488426:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  printTime: 10946.68469786644
  success: true
  timestamp: 1441026488.426892
1441046557526:
  filamentLength: 9858.41851000011
  filamentVolume: 23.71227536225733
  fileName: biggearmod_fixed.gcode
  note: ''
  printTime: 16319.585672855377
  success: false
  timestamp: 1441046557.526706
1441048979224:
  filamentLength: 6067.0780799995355
  filamentVolume: 14.59303294248794
  fileName: calibration_angle.gcode
  note: ''
  success: false
  timestamp: 1441048979.224962
1441049210707:
  filamentLength: 6067.0780799995355
  filamentVolume: 14.59303294248794
  fileName: calibration_angle.gcode
  note: ''
  success: false
  timestamp: 1441049210.707549
1441051972100:
  filamentLength: 6067.0780799995355
  filamentVolume: 14.59303294248794
  fileName: calibration_angle.gcode
  note: ''
  success: false
  timestamp: 1441051972.100817
1441117686377:
  fileName: jonaskuehling_gregs-wade-v3_groovemount.gcode
  note: ''
  success: false
  timestamp: 1441117686.377401
1441117979062:
  filamentLength: 15013.686639997319
  filamentVolume: 36.112148358191014
  fileName: jonaskuehling_gregs-wade-v3_groovemount.gcode
  note: ''
  success: false
  timestamp: 1441117979.062922
1441118293271:
  filamentLength: 15013.686639997319
  filamentVolume: 36.112148358191014
  fileName: jonaskuehling_gregs-wade-v3_groovemount.gcode
  note: ''
  success: false
  timestamp: 1441118293.271045
1441137116161:
  filamentLength: 15013.686639997319
  filamentVolume: 36.112148358191014
  fileName: jonaskuehling_gregs-wade-v3_groovemount.gcode
  note: ''
  printTime: 18773.531893968582
  success: true
  timestamp: 1441137116.161011
1441140577236:
  fileName: Prusa_i3_Hephestos_Mods_-_E3DV6_Ducted_Fan.gcode
  note: ''
  success: false
  timestamp: 1441140577.236729
1441141354623:
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441141354.623782
1441142674825:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441142674.82571
1441144091429:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441144091.429054
1441145832781:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441145832.781173
1441146170244:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441146170.244238
1441146376437:
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441146376.437223
1441146903908:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441146903.908945
1441147123701:
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441147123.701247
1441148222719:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441148222.719519
1441148627402:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441148627.402144
1441185335095:
  filamentLength: 1602.7961300000848
  filamentVolume: 3.8551764814579754
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441185335.095686
1441185828769:
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441185828.769767
1441187473928:
  fileName: Prusa_i3_Hephestos_Mods_-_E3DV6_Ducted_Fan.gcode
  note: ''
  success: false
  timestamp: 1441187473.92839
1441197908388:
  filamentLength: 1442.5164899999293
  filamentVolume: 3.4696587683692135
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441197908.388257
1441198645724:
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  success: false
  timestamp: 1441198645.724329
1441208538996:
  fileName: Prusa_i3_Hephestos_Mods_-_E3DV6_Ducted_Fan.gcode
  note: ''
  printTime: 6187.505659103394
  success: true
  timestamp: 1441208538.996988
1441215226957:
  fileName: prusa-i3-belt-tensioner-good.gcode
  note: ''
  printTime: 2359.3636310100555
  success: true
  timestamp: 1441215226.957835
1441217290941:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1441217290.941874
1441218026970:
  fileName: Rocktopus.gcode
  note: ''
  success: false
  timestamp: 1441218026.970025
1441219934302:
  fileName: Rocktopus.gcode
  note: ''
  printTime: 1888.3349118232727
  success: true
  timestamp: 1441219934.302783
1441223291584:
  fileName: fanguard_20140522-21970-1qcpiry-0.gcode
  note: ''
  printTime: 2860.7214648723602
  success: true
  timestamp: 1441223291.584045
1441230820222:
  fileName: Rocktopus.gcode
  note: ''
  printTime: 3537.2184529304504
  success: true
  timestamp: 1441230820.222664
1441231190619:
  filamentLength: 16938.58204000119
  filamentVolume: 40.742064375870186
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1441231190.619501
1441231393544:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1441231393.544293
1441231600374:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1441231600.374034
1441231805169:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  success: false
  timestamp: 1441231805.16904
1441232370912:
  fileName: Spocktopus_With_Ears_resized.gcode
  note: ''
  success: false
  timestamp: 1441232370.912753
1441245743948:
  fileName: Spocktopus_With_Ears_resized.gcode
  note: ''
  printTime: 10749.48157286644
  success: true
  timestamp: 1441245743.948034
1441281706604:
  fileName: LCD-Controller-without-label.gcode
  note: ''
  printTime: 20492.09854698181
  success: true
  timestamp: 1441281706.604822
1441295222881:
  fileName: Low.gcode
  note: ''
  printTime: 1883.8362500667572
  success: true
  timestamp: 1441295222.881019
1441305278585:
  fileName: LCD_Support.gcode
  note: ''
  printTime: 9995.638012886047
  success: true
  timestamp: 1441305278.585527
1441306792290:
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441306792.290561
1441307600679:
  filamentLength: 2986.505559999832
  filamentVolume: 7.183387694262915
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441307600.679101
1441308065349:
  filamentLength: 2986.505559999832
  filamentVolume: 7.183387694262915
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441308065.349929
1441308616312:
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441308616.312808
1441309041162:
  filamentLength: 2986.505559999832
  filamentVolume: 7.183387694262915
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441309041.162568
1441309353883:
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441309353.883042
1441309539370:
  filamentLength: 2986.505559999832
  filamentVolume: 7.183387694262915
  fileName: LCD_Support.gcode
  note: ''
  success: false
  timestamp: 1441309539.370072
1441364516165:
  fileName: Prusa_i3_Y_Motor_Mount.gcode
  note: ''
  success: false
  timestamp: 1441364516.165872
1441364848220:
  fileName: Prusa_i3_Y_Belt_Clamp_-_0.9mm.gcode
  note: ''
  success: false
  timestamp: 1441364848.220362
1441365075079:
  filamentLength: 3138.7406499999756
  filamentVolume: 7.549555997040862
  fileName: Prusa_i3_Y_Belt_Clamp_-_0.9mm.gcode
  note: ''
  success: false
  timestamp: 1441365075.079445
1441371671197:
  filamentLength: 3138.7406499999756
  filamentVolume: 7.549555997040862
  fileName: Prusa_i3_Y_Belt_Clamp_-_0.9mm.gcode
  note: ''
  printTime: 3915.6735060214996
  success: true
  timestamp: 1441371671.197003
1441378738553:
  filamentLength: 9704.372059999905
  filamentVolume: 23.3417502281014
  fileName: Sensor_Extension.gcode
  note: ''
  success: false
  timestamp: 1441378738.553607
1441379040938:
  fileName: Bracket_-_Main.gcode
  note: ''
  success: false
  timestamp: 1441379040.938891
1441380218337:
  filamentLength: 3508.17982999999
  filamentVolume: 8.438161360759267
  fileName: Bracket_-_Main.gcode
  note: ''
  success: false
  timestamp: 1441380218.337089
1441396883397:
  filamentLength: 3508.17982999999
  filamentVolume: 8.438161360759267
  fileName: Bracket_-_Main.gcode
  note: ''
  success: false
  timestamp: 1441396883.397671
1441402888487:
  fileName: Bracket_-_Main.gcode
  note: ''
  printTime: 5463.998911142349
  success: true
  timestamp: 1441402888.487983
1441403271693:
  fileName: LCD_Support_-_8mm_-_20mm.gcode
  note: ''
  success: false
  timestamp: 1441403271.693932
1441403875086:
  fileName: LCD_Support_-_8mm_-_20mm.gcode
  note: ''
  success: false
  timestamp: 1441403875.086954
1441420028688:
  filamentLength: 5484.180069999889
  filamentVolume: 13.190998923826331
  fileName: LCD_Support_-_8mm_-_20mm.gcode
  note: ''
  printTime: 5556.454829931259
  success: true
  timestamp: 1441420028.688365
1441446515559:
  fileName: Bracket_-_Main.gcode
  note: ''
  printTime: 5079.421332120895
  success: true
  timestamp: 1441446515.559664
1441454995033:
  filamentLength: 7951.935580000021
  filamentVolume: 19.126646524959696
  fileName: Mount_-_Main.gcode
  note: ''
  printTime: 8374.24327492714
  success: true
  timestamp: 1441454995.033266
1441477780006:
  fileName: TendrilFromBeyond.gcode
  note: ''
  printTime: 1427.2061059474945
  success: true
  timestamp: 1441477780.006349
1441479584455:
  fileName: TendrilFromBeyond.gcode
  note: ''
  printTime: 1625.1693749427795
  success: true
  timestamp: 1441479584.455971
1441481653073:
  fileName: TendrilFromBeyond.gcode
  note: ''
  printTime: 1510.3093929290771
  success: true
  timestamp: 1441481653.073648
1441482192909:
  filamentLength: 740.9123200000042
  filamentVolume: 1.7821029745600465
  fileName: TendrilFromBeyond.gcode
  note: ''
  success: false
  timestamp: 1441482192.909794
1441482388743:
  filamentLength: 740.9123200000042
  filamentVolume: 1.7821029745600465
  fileName: TendrilFromBeyond.gcode
  note: ''
  success: false
  timestamp: 1441482388.74394
1441484353265:
  filamentLength: 740.9123200000042
  filamentVolume: 1.7821029745600465
  fileName: TendrilFromBeyond.gcode
  note: ''
  success: false
  timestamp: 1441484353.265637
1441490105238:
  filamentLength: 680.6201899999706
  filamentVolume: 1.6370834070414226
  fileName: C910_webcam_mount_tripod.gcode
  note: ''
  success: false
  timestamp: 1441490105.238467
1441490573484:
  filamentLength: 680.6201899999706
  filamentVolume: 1.6370834070414226
  fileName: C910_webcam_mount_tripod.gcode
  note: ''
  success: false
  timestamp: 1441490573.48437
1441493327082:
  filamentLength: 680.6201899999706
  filamentVolume: 1.6370834070414226
  fileName: C910_webcam_mount_tripod.gcode
  note: ''
  printTime: 1545.7640948295593
  success: true
  timestamp: 1441493327.082356
1441501800792:
  filamentLength: 8640.436529999764
  filamentVolume: 20.782685381192984
  fileName: Sensor_Extension.gcode
  note: ''
  printTime: 8231.4156332016
  success: true
  timestamp: 1441501800.792845
1441524809456:
  fileName: C910_mount_6mmTslot.gcode
  note: ''
  printTime: 2644.511334180832
  success: true
  timestamp: 1441524809.456466
1441532459312:
  filamentLength: 9074.392689999697
  filamentVolume: 21.826472267561037
  fileName: 40mmcube.gcode
  note: ''
  printTime: 6520.1307809352875
  success: true
  timestamp: 1441532459.312883
1441534107948:
  filamentLength: 4733.253359999946
  filamentVolume: 11.384808518506198
  fileName: hollow_cube_20150906-25864-kigrs3-0.gcode
  note: ''
  success: false
  timestamp: 1441534107.948858
1441534570057:
  filamentLength: 4733.253359999946
  filamentVolume: 11.384808518506198
  fileName: hollow_cube_20150906-25864-kigrs3-0.gcode
  note: ''
  success: false
  timestamp: 1441534570.057821
1441542539982:
  filamentLength: 4733.253359999946
  filamentVolume: 11.384808518506198
  fileName: hollow_cube_20150906-25864-kigrs3-0.gcode
  note: ''
  printTime: 6497.888121128082
  success: true
  timestamp: 1441542539.982618
1441543424537:
  filamentLength: 334.3965400000007
  filamentVolume: 0.8043179368600395
  fileName: GrootThickShell.gcode
  note: ''
  success: false
  timestamp: 1441543424.537828
1441545149357:
  fileName: FormlessMaw_EZprint.gcode
  note: ''
  printTime: 1647.0240941047668
  success: true
  timestamp: 1441545149.357631
1441547503143:
  filamentLength: 1208.2496400000032
  filamentVolume: 2.9061809600562434
  fileName: FormlessMaw_EZprint.gcode
  note: ''
  printTime: 1669.0656270980835
  success: true
  timestamp: 1441547503.1438
1441552757954:
  filamentLength: 20672.428949998106
  filamentVolume: 49.72301867402155
  fileName: Prusa_i3_Y_Belt_Clamp_-_0.9mm.gcode
  note: ''
  success: false
  timestamp: 1441552757.95469
1441554037836:
  fileName: Prusa_i3_Y_Idler.gcode
  note: ''
  success: false
  timestamp: 1441554037.836201
1441554156669:
  fileName: Prusa_i3_Y_Idler.gcode
  note: ''
  success: false
  timestamp: 1441554156.669446
1441556115755:
  fileName: Prusa_i3_Y_Idler.gcode
  note: ''
  printTime: 1948.0717160701752
  success: true
  timestamp: 1441556115.75518
1441561120246:
  fileName: hollow_cube_20150906-25864-kigrs3-0.gcode
  note: ''
  printTime: 4939.688787937164
  success: true
  timestamp: 1441561120.246647
1441562853005:
  fileName: prusa-i3-belt-tensioner-good_(1).gcode
  note: ''
  printTime: 1484.7330520153046
  success: true
  timestamp: 1441562853.005402
1441565982401:
  fileName: Endstop_X_Support_Right.gcode
  note: ''
  printTime: 1540.3680548667908
  success: true
  timestamp: 1441565982.401154
1441568141679:
  filamentLength: 1744.6942100000595
  filamentVolume: 4.196481361436638
  fileName: Endstop_X_Support_Left.gcode
  note: ''
  success: false
  timestamp: 1441568141.679014
1441570004943:
  filamentLength: 1744.6942100000595
  filamentVolume: 4.196481361436638
  fileName: Endstop_X_Support_Left.gcode
  note: ''
  printTime: 1824.8706200122833
  success: true
  timestamp: 1441570004.943727
0:
  fileName: Prusa_i3_4_x_Y_Corners.gcode
  note: ''
1441598292017:
  fileName: Prusa_i3_4_x_Y_Corners.gcode
  note: ''
  printTime: 20540.238577127457
  success: true
  timestamp: 1441598292.017892
```

**Comment by imrahil** [comment]
still cannot reproduce... :-/

**Comment by chancrescolex** [comment]
I have this same issue. History panel appears blank. The plugin history.yml has all the print data.

I believe this is the relevant information from octoprint.log:

    2015-11-01 19:41:56,872 - octoprint - ERROR - Exception on /plugin/printhistory/history [GET]
    Traceback (most recent call last):
      File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/__init__.py", line 64, in getHistoryData
        raise IOError("Couldn't read history data from {path}".format(path=self._history_file_path))
    IOError: Couldn't read history data from /home/pi/.octoprint/data/printhistory/history.yaml

**Comment by imrahil** [comment]
if it's possible please attach your history.yaml file or send it to me (email address is in setup.py file)

**Comment by chancrescolex** [comment]
history.yaml

    1443662813747:
      fileName: bearing_20151001-12423-190wjjh-0.gcode
      note: ''
      success: false
      timestamp: 1443662813.747818
    ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@$
      filamentLength: 12200.210159998202
      filamentVolume: 29.344944373971767
      fileName: bearing_20151001-3515-2zs4hf-0.gcode
      note: ''
      success: false
      timestamp: 1443747781.243087
    1443758904471:
      fileName: Double_Spiral_Vase2_SOLID.gcode
      note: ''
      printTime: 10136.74630188942
      success: true
      timestamp: 1443758904.471105
    1443905101283:
      filamentLength: 5314.351910000132
      filamentVolume: 12.78251432864559
      fileName: Twisted_Vase_Basic.gcode
      note: ''
      printTime: 8235.745892047882
      success: true
      timestamp: 1443905101.283733
    1444275143139:
      filamentLength: 4108.9448100004465
      filamentVolume: 9.883170478532222
      fileName: Squeegee_Handle_-_Part_1.gcode
      note: ''
      printTime: 5466.479240179062
      success: true
      timestamp: 1444275143.139481
    1444277877822:
      filamentLength: 2872.753410000137
      filamentVolume: 6.909781709580335
      fileName: Squeegee_Handle_-_Part_1.gcode
      note: ''
      success: false
      timestamp: 1444277877.822802
    1444279014288:
      fileName: Squeegee_Handle_-_Part_1_(1).gcode
      note: ''
      success: false
      timestamp: 1444279014.288751
    1444280643001:
      filamentLength: 2946.488460000134
      filamentVolume: 7.087135288927386
      fileName: Squeegee_Handle_-_Part_1_(1).gcode
      note: ''
      success: false
      timestamp: 1444280643.001647
    1444283721357:
      filamentLength: 2946.488460000134
      filamentVolume: 7.087135288927386
      fileName: Squeegee_Handle_-_Part_1_(1).gcode
      note: ''
      printTime: 3036.207976102829
      success: true
      timestamp: 1444283721.357349
    1444302141971:
      filamentLength: 15565.664729996792
      filamentVolume: 37.439811253687246
      fileName: Squeegee_Handle_-_Prototype_1.gcode
      note: ''
      printTime: 16809.74215888977
      success: true
      timestamp: 1444302141.971034
    1444361865284:
      filamentLength: 15657.819169996885
      filamentVolume: 37.661468657957535
      fileName: Squeegee_Handle_-_Prototype_2.gcode
      note: ''
      success: false
      timestamp: 1444361865.284398
    1444362292848:
      fileName: Squeegee_Handle_-_Prototype_2.gcode
      note: ''
      success: false
      timestamp: 1444362292.848677
    1444362997574:
      filamentLength: 15657.819169996885
      filamentVolume: 37.661468657957535
      fileName: Squeegee_Handle_-_Prototype_2.gcode
      note: ''
      success: false
      timestamp: 1444362997.574447
    1444364860057:
      filamentLength: 16208.785240008254
      filamentVolume: 37.66146790862875
      fileName: Squeegee_Handle_-_Prototype_2.gcode
      note: ''
      success: false
      timestamp: 1444364860.057109
    1444550225827:
      filamentLength: 15331.447450000289
      filamentVolume: 35.622954316514836
      fileName: 74.5mm_Oil_Filter_Wrench.gcode
      note: ''
      printTime: 15625.571340084076
      success: true
      timestamp: 1444550225.827733
    1444591073224:
      filamentLength: 15055.867079999522
      filamentVolume: 34.982637284278894
      fileName: 74.5mm_Oil_Filter_Wrench_102.gcode
      note: ''
      printTime: 15530.26522397995
      success: true
      timestamp: 1444591073.224015
    1444807247570:
      filamentLength: 17507.414699999765
      filamentVolume: 40.67886193344127
      fileName: Squeegee_Handle_-_Prototype_2.gcode
      note: ''
      printTime: 17729.1596159935
      success: true
      timestamp: 1444807247.570324

**Comment by imrahil** [comment]
you see that strange line at the beginning of the file? what the heck is that? :) if you remove it and restart Octoprint, history plugin works fine...

**Comment by chancrescolex** [comment]
Thanks, that did the trick. No idea what that line was or where it came from.
