### ISSUE TITLE
Error while writing to history.yaml

### ISSUE THREAD

**Issue by sohilnandu** [imrahil/OctoPrint-PrintHistory#30]
Ever since I updated to the latest version of the plugin I've been getting this error when trying to write to the history.yaml file.

```
2016-04-06 06:35:06,619 - octoprint.plugin - ERROR - Error while calling plugin printhistory
Traceback (most recent call last):
  File "/home/ubuntu/OctoPrint/src/octoprint/plugin/__init__.py", line 204, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/octoprint_printhistory/__init__.py", line 63, in on_event
    return eventHandler.eventHandler(self, event, payload)
  File "/usr/local/lib/python2.7/dist-packages/octoprint_printhistory/eventHandler.py", line 115, in eventHandler
    self._console_logger.exception("Error while writing history.yaml to {path}".format(**locals()))
KeyError: 'path'
```

**Comment by imrahil** [comment]
Anyone else have this problem?
