### ISSUE TITLE
octoprint.plugin - ERROR 

### ISSUE THREAD

**Issue by kjones200** [imrahil/OctoPrint-PrintHistory#40]
Printhistory is not working on my raspberry pi 3 running octoprint 1.3.0.  I installed PrintHistory from the plugin manager.

Here is there error message from the octoprint.log:

`
2017-01-01 05:18:21,162 - octoprint.plugin - ERROR - Error while calling plugin printhistory
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/__init__.py", line 118, in on_event
    return eventHandler.eventHandler(self, event, payload)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/eventHandler.py", line 97, in eventHandler
    cur.execute("INSERT INTO print_history (fileName, note, filamentVolume, filamentLength, printTime, success, timestamp) VALUES (:fileName, :note, :filamentVolume, :filamentLength, :printTime, :success, :timestamp)", currentFile)
ProgrammingError: You did not supply a value for binding 3.
`

Any assistance would be greatly appreciated.

**Comment by imrahil** [comment]
Fixed in 1.1
